package constants

var Timezones = []string{
	"Africa/Abidjan",
	"Africa/Accra",
	"Africa/Addis_Ababa",
	"Africa/Algiers",
	"Africa/Asmara",
	"Africa/Bamako",
	"Africa/Bangui",
	"Africa/Banjul",
	"Africa/Bissau",
	"Africa/Blantyre",
	"Africa/Brazzaville",
	"Africa/Bujumbura",
	"Africa/Cairo",
	"Africa/Casablanca",
	"Africa/Ceuta",
	"Africa/Conakry",
	"Africa/Dakar",
	"Africa/Dar_es_Salaam",
	"Africa/Djibouti",
	"Africa/Douala",
	"Africa/El_Aaiun",
	"Africa/Freetown",
	"Africa/Gaborone",
	"Africa/Harare",
	"Africa/Johannesburg",
	"Africa/Juba",
	"Africa/Kampala",
	"Africa/Khartoum",
	"Africa/Kigali",
	"Africa/Kinshasa",
	"Africa/Lagos",
	"Africa/Libreville",
	"Africa/Lome",
	"Africa/Luanda",
	"Africa/Lubumbashi",
	"Africa/Lusaka",
	"Africa/Malabo",
	"Africa/Maputo",
	"Africa/Maseru",
	"Africa/Mbabane",
	"Africa/Mogadishu",
	"Africa/Monrovia",
	"Africa/Nairobi",
	"Africa/Ndjamena",
	"Africa/Niamey",
	"Africa/Nouakchott",
	"Africa/Ouagadougou",
	"Africa/Porto-Novo",
	"Africa/Sao_Tome",
	"Africa/Tripoli",
	"Africa/Tunis",
	"Africa/Windhoek",
	"America/Adak",
	"America/Anchorage",
	"America/Anguilla",
	"America/Antigua",
	"America/Araguaina",
	"America/Argentina/Buenos_Aires",
	"America/Argentina/Catamarca",
	"America/Argentina/Cordoba",
	"America/Argentina/Jujuy",
	"America/Argentina/La_Rioja",
	"America/Argentina/Mendoza",
	"America/Argentina/Rio_Gallegos",
	"America/Argentina/Salta",
	"America/Argentina/San_Juan",
	"America/Argentina/San_Luis",
	"America/Argentina/Tucuman",
	"America/Argentina/Ushuaia",
	"America/Aruba",
	"America/Asuncion",
	"America/Atikokan",
	"America/Bahia",
	"America/Bahia_Banderas",
	"America/Barbados",
	"America/Belem",
	"America/Belize",
	"America/Blanc-Sablon",
	"America/Boa_Vista",
	"America/Bogota",
	"America/Boise",
	"America/Cambridge_Bay",
	"America/Campo_Grande",
	"America/Cancun",
	"America/Caracas",
	"America/Cayenne",
	"America/Cayman",
	"America/Chicago",
	"America/Chihuahua",
	"America/Ciudad_Juarez",
	"America/Costa_Rica",
	"America/Coyhaique",
	"America/Creston",
	"America/Cuiaba",
	"America/Curacao",
	"America/Danmarkshavn",
	"America/Dawson",
	"America/Dawson_Creek",
	"America/Denver",
	"America/Detroit",
	"America/Dominica",
	"America/Edmonton",
	"America/Eirunepe",
	"America/El_Salvador",
	"America/Fort_Nelson",
	"America/Fortaleza",
	"America/Glace_Bay",
	"America/Godthab",
	"America/Goose_Bay",
	"America/Grand_Turk",
	"America/Grenada",
	"America/Guadeloupe",
	"America/Guatemala",
	"America/Guayaquil",
	"America/Guyana",
	"America/Halifax",
	"America/Havana",
	"America/Hermosillo",
	"America/Indiana/Indianapolis",
	"America/Indiana/Knox",
	"America/Indiana/Marengo",
	"America/Indiana/Petersburg",
	"America/Indiana/Tell_City",
	"America/Indiana/Vevay",
	"America/Indiana/Vincennes",
	"America/Indiana/Winamac",
	"America/Inuvik",
	"America/Iqaluit",
	"America/Jamaica",
	"America/Juneau",
	"America/Kentucky/Louisville",
	"America/Kentucky/Monticello",
	"America/Kralendijk",
	"America/La_Paz",
	"America/Lima",
	"America/Los_Angeles",
	"America/Lower_Princes",
	"America/Maceio",
	"America/Managua",
	"America/Manaus",
	"America/Marigot",
	"America/Martinique",
	"America/Matamoros",
	"America/Mazatlan",
	"America/Menominee",
	"America/Merida",
	"America/Metlakatla",
	"America/Mexico_City",
	"America/Miquelon",
	"America/Moncton",
	"America/Monterrey",
	"America/Montevideo",
	"America/Montreal",
	"America/Montserrat",
	"America/Nassau",
	"America/New_York",
	"America/Nipigon",
	"America/Nome",
	"America/Noronha",
	"America/North_Dakota/Beulah",
	"America/North_Dakota/Center",
	"America/North_Dakota/New_Salem",
	"America/Nuuk",
	"America/Ojinaga",
	"America/Panama",
	"America/Pangnirtung",
	"America/Paramaribo",
	"America/Phoenix",
	"America/Port-au-Prince",
	"America/Port_of_Spain",
	"America/Porto_Velho",
	"America/Puerto_Rico",
	"America/Punta_Arenas",
	"America/Rainy_River",
	"America/Rankin_Inlet",
	"America/Recife",
	"America/Regina",
	"America/Resolute",
	"America/Rio_Branco",
	"America/Santa_Isabel",
	"America/Santarem",
	"America/Santiago",
	"America/Santo_Domingo",
	"America/Sao_Paulo",
	"America/Scoresbysund",
	"America/Shiprock",
	"America/Sitka",
	"America/St_Barthelemy",
	"America/St_Johns",
	"America/St_Kitts",
	"America/St_Lucia",
	"America/St_Thomas",
	"America/St_Vincent",
	"America/Swift_Current",
	"America/Tegucigalpa",
	"America/Thule",
	"America/Thunder_Bay",
	"America/Tijuana",
	"America/Toronto",
	"America/Tortola",
	"America/Vancouver",
	"America/Whitehorse",
	"America/Winnipeg",
	"America/Yakutat",
	"America/Yellowknife",
	"Antarctica/Casey",
	"Antarctica/Davis",
	"Antarctica/DumontDUrville",
	"Antarctica/Macquarie",
	"Antarctica/Mawson",
	"Antarctica/McMurdo",
	"Antarctica/Palmer",
	"Antarctica/Rothera",
	"Antarctica/South_Pole",
	"Antarctica/Syowa",
	"Antarctica/Troll",
	"Antarctica/Vostok",
	"Arctic/Longyearbyen",
	"Asia/Aden",
	"Asia/Almaty",
	"Asia/Amman",
	"Asia/Anadyr",
	"Asia/Aqtau",
	"Asia/Aqtobe",
	"Asia/Ashgabat",
	"Asia/Atyrau",
	"Asia/Baghdad",
	"Asia/Bahrain",
	"Asia/Baku",
	"Asia/Bangkok",
	"Asia/Barnaul",
	"Asia/Beirut",
	"Asia/Bishkek",
	"Asia/Brunei",
	"Asia/Calcutta",
	"Asia/Chita",
	"Asia/Choibalsan",
	"Asia/Chongqing",
	"Asia/Colombo",
	"Asia/Damascus",
	"Asia/Dhaka",
	"Asia/Dili",
	"Asia/Dubai",
	"Asia/Dushanbe",
	"Asia/Famagusta",
	"Asia/Gaza",
	"Asia/Harbin",
	"Asia/Hebron",
	"Asia/Ho_Chi_Minh",
	"Asia/Hong_Kong",
	"Asia/Hovd",
	"Asia/Irkutsk",
	"Asia/Jakarta",
	"Asia/Jayapura",
	"Asia/Jerusalem",
	"Asia/Kabul",
	"Asia/Kamchatka",
	"Asia/Karachi",
	"Asia/Kashgar",
	"Asia/Kathmandu",
	"Asia/Katmandu",
	"Asia/Khandyga",
	"Asia/Krasnoyarsk",
	"Asia/Kuala_Lumpur",
	"Asia/Kuching",
	"Asia/Kuwait",
	"Asia/Macau",
	"Asia/Magadan",
	"Asia/Makassar",
	"Asia/Manila",
	"Asia/Muscat",
	"Asia/Nicosia",
	"Asia/Novokuznetsk",
	"Asia/Novosibirsk",
	"Asia/Omsk",
	"Asia/Oral",
	"Asia/Phnom_Penh",
	"Asia/Pontianak",
	"Asia/Pyongyang",
	"Asia/Qatar",
	"Asia/Qostanay",
	"Asia/Qyzylorda",
	"Asia/Rangoon",
	"Asia/Riyadh",
	"Asia/Sakhalin",
	"Asia/Samarkand",
	"Asia/Seoul",
	"Asia/Shanghai",
	"Asia/Singapore",
	"Asia/Srednekolymsk",
	"Asia/Taipei",
	"Asia/Tashkent",
	"Asia/Tbilisi",
	"Asia/Tehran",
	"Asia/Thimphu",
	"Asia/Tokyo",
	"Asia/Tomsk",
	"Asia/Ulaanbaatar",
	"Asia/Urumqi",
	"Asia/Ust-Nera",
	"Asia/Vientiane",
	"Asia/Vladivostok",
	"Asia/Yakutsk",
	"Asia/Yangon",
	"Asia/Yekaterinburg",
	"Asia/Yerevan",
	"Atlantic/Azores",
	"Atlantic/Bermuda",
	"Atlantic/Canary",
	"Atlantic/Cape_Verde",
	"Atlantic/Faroe",
	"Atlantic/Madeira",
	"Atlantic/Reykjavik",
	"Atlantic/South_Georgia",
	"Atlantic/St_Helena",
	"Atlantic/Stanley",
	"Australia/Adelaide",
	"Australia/Brisbane",
	"Australia/Broken_Hill",
	"Australia/Currie",
	"Australia/Darwin",
	"Australia/Eucla",
	"Australia/Hobart",
	"Australia/Lindeman",
	"Australia/Lord_Howe",
	"Australia/Melbourne",
	"Australia/Perth",
	"Australia/Sydney",
	"Europe/Amsterdam",
	"Europe/Andorra",
	"Europe/Astrakhan",
	"Europe/Athens",
	"Europe/Belgrade",
	"Europe/Berlin",
	"Europe/Bratislava",
	"Europe/Brussels",
	"Europe/Bucharest",
	"Europe/Budapest",
	"Europe/Busingen",
	"Europe/Chisinau",
	"Europe/Copenhagen",
	"Europe/Dublin",
	"Europe/Gibraltar",
	"Europe/Guernsey",
	"Europe/Helsinki",
	"Europe/Isle_of_Man",
	"Europe/Istanbul",
	"Europe/Jersey",
	"Europe/Kaliningrad",
	"Europe/Kiev",
	"Europe/Kirov",
	"Europe/Kyiv",
	"Europe/Lisbon",
	"Europe/Ljubljana",
	"Europe/London",
	"Europe/Luxembourg",
	"Europe/Madrid",
	"Europe/Malta",
	"Europe/Mariehamn",
	"Europe/Minsk",
	"Europe/Monaco",
	"Europe/Moscow",
	"Europe/Oslo",
	"Europe/Paris",
	"Europe/Podgorica",
	"Europe/Prague",
	"Europe/Riga",
	"Europe/Rome",
	"Europe/Samara",
	"Europe/San_Marino",
	"Europe/Sarajevo",
	"Europe/Saratov",
	"Europe/Simferopol",
	"Europe/Skopje",
	"Europe/Sofia",
	"Europe/Stockholm",
	"Europe/Tallinn",
	"Europe/Tirane",
	"Europe/Ulyanovsk",
	"Europe/Uzhgorod",
	"Europe/Vaduz",
	"Europe/Vatican",
	"Europe/Vienna",
	"Europe/Vilnius",
	"Europe/Volgograd",
	"Europe/Warsaw",
	"Europe/Zagreb",
	"Europe/Zaporozhye",
	"Europe/Zurich",
	"Indian/Antananarivo",
	"Indian/Chagos",
	"Indian/Christmas",
	"Indian/Cocos",
	"Indian/Comoro",
	"Indian/Kerguelen",
	"Indian/Mahe",
	"Indian/Maldives",
	"Indian/Mauritius",
	"Indian/Mayotte",
	"Indian/Reunion",
	"Pacific/Apia",
	"Pacific/Auckland",
	"Pacific/Bougainville",
	"Pacific/Chatham",
	"Pacific/Chuuk",
	"Pacific/Easter",
	"Pacific/Efate",
	"Pacific/Enderbury",
	"Pacific/Fakaofo",
	"Pacific/Fiji",
	"Pacific/Funafuti",
	"Pacific/Galapagos",
	"Pacific/Gambier",
	"Pacific/Guadalcanal",
	"Pacific/Guam",
	"Pacific/Honolulu",
	"Pacific/Johnston",
	"Pacific/Kanton",
	"Pacific/Kiritimati",
	"Pacific/Kosrae",
	"Pacific/Kwajalein",
	"Pacific/Majuro",
	"Pacific/Marquesas",
	"Pacific/Midway",
	"Pacific/Nauru",
	"Pacific/Niue",
	"Pacific/Norfolk",
	"Pacific/Noumea",
	"Pacific/Pago_Pago",
	"Pacific/Palau",
	"Pacific/Pitcairn",
	"Pacific/Pohnpei",
	"Pacific/Ponape",
	"Pacific/Port_Moresby",
	"Pacific/Rarotonga",
	"Pacific/Saipan",
	"Pacific/Tahiti",
	"Pacific/Tarawa",
	"Pacific/Tongatapu",
	"Pacific/Truk",
	"Pacific/Wake",
	"Pacific/Wallis",
}

var TimezoneMap = map[int]string{
	1:   "Africa/Abidjan",
	2:   "Africa/Accra",
	3:   "Africa/Addis_Ababa",
	4:   "Africa/Algiers",
	5:   "Africa/Asmara",
	6:   "Africa/Bamako",
	7:   "Africa/Bangui",
	8:   "Africa/Banjul",
	9:   "Africa/Bissau",
	10:  "Africa/Blantyre",
	11:  "Africa/Brazzaville",
	12:  "Africa/Bujumbura",
	13:  "Africa/Cairo",
	14:  "Africa/Casablanca",
	15:  "Africa/Ceuta",
	16:  "Africa/Conakry",
	17:  "Africa/Dakar",
	18:  "Africa/Dar_es_Salaam",
	19:  "Africa/Djibouti",
	20:  "Africa/Douala",
	21:  "Africa/El_Aaiun",
	22:  "Africa/Freetown",
	23:  "Africa/Gaborone",
	24:  "Africa/Harare",
	25:  "Africa/Johannesburg",
	26:  "Africa/Juba",
	27:  "Africa/Kampala",
	28:  "Africa/Khartoum",
	29:  "Africa/Kigali",
	30:  "Africa/Kinshasa",
	31:  "Africa/Lagos",
	32:  "Africa/Libreville",
	33:  "Africa/Lome",
	34:  "Africa/Luanda",
	35:  "Africa/Lubumbashi",
	36:  "Africa/Lusaka",
	37:  "Africa/Malabo",
	38:  "Africa/Maputo",
	39:  "Africa/Maseru",
	40:  "Africa/Mbabane",
	41:  "Africa/Mogadishu",
	42:  "Africa/Monrovia",
	43:  "Africa/Nairobi",
	44:  "Africa/Ndjamena",
	45:  "Africa/Niamey",
	46:  "Africa/Nouakchott",
	47:  "Africa/Ouagadougou",
	48:  "Africa/Porto-Novo",
	49:  "Africa/Sao_Tome",
	50:  "Africa/Tripoli",
	51:  "Africa/Tunis",
	52:  "Africa/Windhoek",
	53:  "America/Adak",
	54:  "America/Anchorage",
	55:  "America/Anguilla",
	56:  "America/Antigua",
	57:  "America/Araguaina",
	58:  "America/Argentina/Buenos_Aires",
	59:  "America/Argentina/Catamarca",
	60:  "America/Argentina/Cordoba",
	61:  "America/Argentina/Jujuy",
	62:  "America/Argentina/La_Rioja",
	63:  "America/Argentina/Mendoza",
	64:  "America/Argentina/Rio_Gallegos",
	65:  "America/Argentina/Salta",
	66:  "America/Argentina/San_Juan",
	67:  "America/Argentina/San_Luis",
	68:  "America/Argentina/Tucuman",
	69:  "America/Argentina/Ushuaia",
	70:  "America/Aruba",
	71:  "America/Asuncion",
	72:  "America/Atikokan",
	73:  "America/Bahia",
	74:  "America/Bahia_Banderas",
	75:  "America/Barbados",
	76:  "America/Belem",
	77:  "America/Belize",
	78:  "America/Blanc-Sablon",
	79:  "America/Boa_Vista",
	80:  "America/Bogota",
	81:  "America/Boise",
	82:  "America/Cambridge_Bay",
	83:  "America/Campo_Grande",
	84:  "America/Cancun",
	85:  "America/Caracas",
	86:  "America/Cayenne",
	87:  "America/Cayman",
	88:  "America/Chicago",
	89:  "America/Chihuahua",
	90:  "America/Ciudad_Juarez",
	91:  "America/Costa_Rica",
	92:  "America/Coyhaique",
	93:  "America/Creston",
	94:  "America/Cuiaba",
	95:  "America/Curacao",
	96:  "America/Danmarkshavn",
	97:  "America/Dawson",
	98:  "America/Dawson_Creek",
	99:  "America/Denver",
	100: "America/Detroit",
	101: "America/Dominica",
	102: "America/Edmonton",
	103: "America/Eirunepe",
	104: "America/El_Salvador",
	105: "America/Fort_Nelson",
	106: "America/Fortaleza",
	107: "America/Glace_Bay",
	108: "America/Godthab",
	109: "America/Goose_Bay",
	110: "America/Grand_Turk",
	111: "America/Grenada",
	112: "America/Guadeloupe",
	113: "America/Guatemala",
	114: "America/Guayaquil",
	115: "America/Guyana",
	116: "America/Halifax",
	117: "America/Havana",
	118: "America/Hermosillo",
	119: "America/Indiana/Indianapolis",
	120: "America/Indiana/Knox",
	121: "America/Indiana/Marengo",
	122: "America/Indiana/Petersburg",
	123: "America/Indiana/Tell_City",
	124: "America/Indiana/Vevay",
	125: "America/Indiana/Vincennes",
	126: "America/Indiana/Winamac",
	127: "America/Inuvik",
	128: "America/Iqaluit",
	129: "America/Jamaica",
	130: "America/Juneau",
	131: "America/Kentucky/Louisville",
	132: "America/Kentucky/Monticello",
	133: "America/Kralendijk",
	134: "America/La_Paz",
	135: "America/Lima",
	136: "America/Los_Angeles",
	137: "America/Lower_Princes",
	138: "America/Maceio",
	139: "America/Managua",
	140: "America/Manaus",
	141: "America/Marigot",
	142: "America/Martinique",
	143: "America/Matamoros",
	144: "America/Mazatlan",
	145: "America/Menominee",
	146: "America/Merida",
	147: "America/Metlakatla",
	148: "America/Mexico_City",
	149: "America/Miquelon",
	150: "America/Moncton",
	151: "America/Monterrey",
	152: "America/Montevideo",
	153: "America/Montreal",
	154: "America/Montserrat",
	155: "America/Nassau",
	156: "America/New_York",
	157: "America/Nipigon",
	158: "America/Nome",
	159: "America/Noronha",
	160: "America/North_Dakota/Beulah",
	161: "America/North_Dakota/Center",
	162: "America/North_Dakota/New_Salem",
	163: "America/Nuuk",
	164: "America/Ojinaga",
	165: "America/Panama",
	166: "America/Pangnirtung",
	167: "America/Paramaribo",
	168: "America/Phoenix",
	169: "America/Port-au-Prince",
	170: "America/Port_of_Spain",
	171: "America/Porto_Velho",
	172: "America/Puerto_Rico",
	173: "America/Punta_Arenas",
	174: "America/Rainy_River",
	175: "America/Rankin_Inlet",
	176: "America/Recife",
	177: "America/Regina",
	178: "America/Resolute",
	179: "America/Rio_Branco",
	180: "America/Santa_Isabel",
	181: "America/Santarem",
	182: "America/Santiago",
	183: "America/Santo_Domingo",
	184: "America/Sao_Paulo",
	185: "America/Scoresbysund",
	186: "America/Shiprock",
	187: "America/Sitka",
	188: "America/St_Barthelemy",
	189: "America/St_Johns",
	190: "America/St_Kitts",
	191: "America/St_Lucia",
	192: "America/St_Thomas",
	193: "America/St_Vincent",
	194: "America/Swift_Current",
	195: "America/Tegucigalpa",
	196: "America/Thule",
	197: "America/Thunder_Bay",
	198: "America/Tijuana",
	199: "America/Toronto",
	200: "America/Tortola",
	201: "America/Vancouver",
	202: "America/Whitehorse",
	203: "America/Winnipeg",
	204: "America/Yakutat",
	205: "America/Yellowknife",
	206: "Antarctica/Casey",
	207: "Antarctica/Davis",
	208: "Antarctica/DumontDUrville",
	209: "Antarctica/Macquarie",
	210: "Antarctica/Mawson",
	211: "Antarctica/McMurdo",
	212: "Antarctica/Palmer",
	213: "Antarctica/Rothera",
	214: "Antarctica/South_Pole",
	215: "Antarctica/Syowa",
	216: "Antarctica/Troll",
	217: "Antarctica/Vostok",
	218: "Arctic/Longyearbyen",
	219: "Asia/Aden",
	220: "Asia/Almaty",
	221: "Asia/Amman",
	222: "Asia/Anadyr",
	223: "Asia/Aqtau",
	224: "Asia/Aqtobe",
	225: "Asia/Ashgabat",
	226: "Asia/Atyrau",
	227: "Asia/Baghdad",
	228: "Asia/Bahrain",
	229: "Asia/Baku",
	230: "Asia/Bangkok",
	231: "Asia/Barnaul",
	232: "Asia/Beirut",
	233: "Asia/Bishkek",
	234: "Asia/Brunei",
	235: "Asia/Calcutta",
	236: "Asia/Chita",
	237: "Asia/Choibalsan",
	238: "Asia/Chongqing",
	239: "Asia/Colombo",
	240: "Asia/Damascus",
	241: "Asia/Dhaka",
	242: "Asia/Dili",
	243: "Asia/Dubai",
	244: "Asia/Dushanbe",
	245: "Asia/Famagusta",
	246: "Asia/Gaza",
	247: "Asia/Harbin",
	248: "Asia/Hebron",
	249: "Asia/Ho_Chi_Minh",
	250: "Asia/Hong_Kong",
	251: "Asia/Hovd",
	252: "Asia/Irkutsk",
	253: "Asia/Jakarta",
	254: "Asia/Jayapura",
	255: "Asia/Jerusalem",
	256: "Asia/Kabul",
	257: "Asia/Kamchatka",
	258: "Asia/Karachi",
	259: "Asia/Kashgar",
	260: "Asia/Kathmandu",
	261: "Asia/Katmandu",
	262: "Asia/Khandyga",
	263: "Asia/Krasnoyarsk",
	264: "Asia/Kuala_Lumpur",
	265: "Asia/Kuching",
	266: "Asia/Kuwait",
	267: "Asia/Macau",
	268: "Asia/Magadan",
	269: "Asia/Makassar",
	270: "Asia/Manila",
	271: "Asia/Muscat",
	272: "Asia/Nicosia",
	273: "Asia/Novokuznetsk",
	274: "Asia/Novosibirsk",
	275: "Asia/Omsk",
	276: "Asia/Oral",
	277: "Asia/Phnom_Penh",
	278: "Asia/Pontianak",
	279: "Asia/Pyongyang",
	280: "Asia/Qatar",
	281: "Asia/Qostanay",
	282: "Asia/Qyzylorda",
	283: "Asia/Rangoon",
	284: "Asia/Riyadh",
	285: "Asia/Sakhalin",
	286: "Asia/Samarkand",
	287: "Asia/Seoul",
	288: "Asia/Shanghai",
	289: "Asia/Singapore",
	290: "Asia/Srednekolymsk",
	291: "Asia/Taipei",
	292: "Asia/Tashkent",
	293: "Asia/Tbilisi",
	294: "Asia/Tehran",
	295: "Asia/Thimphu",
	296: "Asia/Tokyo",
	297: "Asia/Tomsk",
	298: "Asia/Ulaanbaatar",
	299: "Asia/Urumqi",
	300: "Asia/Ust-Nera",
	301: "Asia/Vientiane",
	302: "Asia/Vladivostok",
	303: "Asia/Yakutsk",
	304: "Asia/Yangon",
	305: "Asia/Yekaterinburg",
	306: "Asia/Yerevan",
	307: "Atlantic/Azores",
	308: "Atlantic/Bermuda",
	309: "Atlantic/Canary",
	310: "Atlantic/Cape_Verde",
	311: "Atlantic/Faroe",
	312: "Atlantic/Madeira",
	313: "Atlantic/Reykjavik",
	314: "Atlantic/South_Georgia",
	315: "Atlantic/St_Helena",
	316: "Atlantic/Stanley",
	317: "Australia/Adelaide",
	318: "Australia/Brisbane",
	319: "Australia/Broken_Hill",
	320: "Australia/Currie",
	321: "Australia/Darwin",
	322: "Australia/Eucla",
	323: "Australia/Hobart",
	324: "Australia/Lindeman",
	325: "Australia/Lord_Howe",
	326: "Australia/Melbourne",
	327: "Australia/Perth",
	328: "Australia/Sydney",
	329: "Europe/Amsterdam",
	330: "Europe/Andorra",
	331: "Europe/Astrakhan",
	332: "Europe/Athens",
	333: "Europe/Belgrade",
	334: "Europe/Berlin",
	335: "Europe/Bratislava",
	336: "Europe/Brussels",
	337: "Europe/Bucharest",
	338: "Europe/Budapest",
	339: "Europe/Busingen",
	340: "Europe/Chisinau",
	341: "Europe/Copenhagen",
	342: "Europe/Dublin",
	343: "Europe/Gibraltar",
	344: "Europe/Guernsey",
	345: "Europe/Helsinki",
	346: "Europe/Isle_of_Man",
	347: "Europe/Istanbul",
	348: "Europe/Jersey",
	349: "Europe/Kaliningrad",
	350: "Europe/Kiev",
	351: "Europe/Kirov",
	352: "Europe/Kyiv",
	353: "Europe/Lisbon",
	354: "Europe/Ljubljana",
	355: "Europe/London",
	356: "Europe/Luxembourg",
	357: "Europe/Madrid",
	358: "Europe/Malta",
	359: "Europe/Mariehamn",
	360: "Europe/Minsk",
	361: "Europe/Monaco",
	362: "Europe/Moscow",
	363: "Europe/Oslo",
	364: "Europe/Paris",
	365: "Europe/Podgorica",
	366: "Europe/Prague",
	367: "Europe/Riga",
	368: "Europe/Rome",
	369: "Europe/Samara",
	370: "Europe/San_Marino",
	371: "Europe/Sarajevo",
	372: "Europe/Saratov",
	373: "Europe/Simferopol",
	374: "Europe/Skopje",
	375: "Europe/Sofia",
	376: "Europe/Stockholm",
	377: "Europe/Tallinn",
	378: "Europe/Tirane",
	379: "Europe/Ulyanovsk",
	380: "Europe/Uzhgorod",
	381: "Europe/Vaduz",
	382: "Europe/Vatican",
	383: "Europe/Vienna",
	384: "Europe/Vilnius",
	385: "Europe/Volgograd",
	386: "Europe/Warsaw",
	387: "Europe/Zagreb",
	388: "Europe/Zaporozhye",
	389: "Europe/Zurich",
	390: "Indian/Antananarivo",
	391: "Indian/Chagos",
	392: "Indian/Christmas",
	393: "Indian/Cocos",
	394: "Indian/Comoro",
	395: "Indian/Kerguelen",
	396: "Indian/Mahe",
	397: "Indian/Maldives",
	398: "Indian/Mauritius",
	399: "Indian/Mayotte",
	400: "Indian/Reunion",
	401: "Pacific/Apia",
	402: "Pacific/Auckland",
	403: "Pacific/Bougainville",
	404: "Pacific/Chatham",
	405: "Pacific/Chuuk",
	406: "Pacific/Easter",
	407: "Pacific/Efate",
	408: "Pacific/Enderbury",
	409: "Pacific/Fakaofo",
	410: "Pacific/Fiji",
	411: "Pacific/Funafuti",
	412: "Pacific/Galapagos",
	413: "Pacific/Gambier",
	414: "Pacific/Guadalcanal",
	415: "Pacific/Guam",
	416: "Pacific/Honolulu",
	417: "Pacific/Johnston",
	418: "Pacific/Kanton",
	419: "Pacific/Kiritimati",
	420: "Pacific/Kosrae",
	421: "Pacific/Kwajalein",
	422: "Pacific/Majuro",
	423: "Pacific/Marquesas",
	424: "Pacific/Midway",
	425: "Pacific/Nauru",
	426: "Pacific/Niue",
	427: "Pacific/Norfolk",
	428: "Pacific/Noumea",
	429: "Pacific/Pago_Pago",
	430: "Pacific/Palau",
	431: "Pacific/Pitcairn",
	432: "Pacific/Pohnpei",
	433: "Pacific/Ponape",
	434: "Pacific/Port_Moresby",
	435: "Pacific/Rarotonga",
	436: "Pacific/Saipan",
	437: "Pacific/Tahiti",
	438: "Pacific/Tarawa",
	439: "Pacific/Tongatapu",
	440: "Pacific/Truk",
	441: "Pacific/Wake",
	442: "Pacific/Wallis",
}
