// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTimezone(arg1) {
  return window['go']['main']['App']['AddTimezone'](arg1);
}

export function GetTimezoneList() {
  return window['go']['main']['App']['GetTimezoneList']();
}

export function GetTimezones() {
  return window['go']['main']['App']['GetTimezones']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RemoveTimezone(arg1) {
  return window['go']['main']['App']['RemoveTimezone'](arg1);
}
