// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function AddTimezone(arg1:string):Promise<void>;

export function GetTimezoneList():Promise<Array<db.TimezoneEntry>>;

export function GetTimezones():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTimezone(arg1:string):Promise<void>;
